### ISSUE TITLE
viewpager中的recyclerview和本身tabBehavior的同向滑动可以处理吗

### ISSUE THREAD

**Issue by wzsxlh** [CSnowStack/BehaviorDemo#1]
希望的效果就是，在头部展开的时候，上下滑动时不会影响到recyclerview，在头部隐藏的时候，如果当前位置处于recyclerview顶部，手指上滑时是recylerview正常的滑动，而手指下滑时recylerview不动，展开头部，如果当前位置不是在recylerview顶部，则滑动事件全部由recyclerview本身处理。
这种效果可以做到吗？求教一下。

**Comment by CSnowStack** [comment]
好了
