### ISSUE TITLE
Behavior Demo Greatly Changed

### ISSUE THREAD

**Issue by rayliverified** [CSnowStack/BehaviorDemo#3]
Commit ea4c6a7c1d889044a48e644e4a368c0637174c6d on April 26th changed the effect of this library. What is the reason for this change? May I suggest that when you create a new effect, to start a new library? This change confused me greatly before looking through the commit history because the references to this library still use the old GIF. 

This is an amazing library and the current effect is amazing too! I would suggest creating a new library with the current effect and then revert this library to the original effect to maintain consistency. The changes made so far completely rewrite this library! 

Please let me know what you think!

**Comment by CSnowStack** [comment]
大兄弟,我英文很差,只能机翻了,当然是骗star了,上个库骗不到100个,好气,现在骗到100个了,很满足,太菜了,没办法

**Comment by rayliverified** [comment]
Ok, I understand. I think you would get even better results if you kept the old code and included it back in this library. This library is a "Behavior Demo" after all and the previous behavior was very good!
